"""Add booking model

Revision ID: 50ce71265d2c
Revises: 0001
Create Date: 2026-09-25 01:22:09.653425
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '50ce71265d2c'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.drop_constraint(op.f('uq_levels_slug'), 'levels', type_='unique')
    op.drop_index(op.f('ix_levels_slug'), table_name='levels')
    op.create_index(op.f('ix_levels_slug'), 'levels', ['slug'], unique=True)
    op.create_index(op.f('ix_levels_id'), 'levels', ['id'], unique=False)
    op.drop_constraint(op.f('uq_locations_slug'), 'locations', type_='unique')
    op.drop_index(op.f('ix_locations_slug'), table_name='locations')
    op.create_index(op.f('ix_locations_slug'), 'locations', ['slug'], unique=True)
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.drop_index(op.f('ix_reviews_booking_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_tutor_profile_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.create_index(op.f('ix_reviews_id'), 'reviews', ['id'], unique=False)
    op.drop_constraint(op.f('uq_subjects_slug'), 'subjects', type_='unique')
    op.drop_index(op.f('ix_subjects_slug'), table_name='subjects')
    op.create_index(op.f('ix_subjects_slug'), 'subjects', ['slug'], unique=True)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.drop_index(op.f('ix_tutor_availabilities_tutor_profile_id'), table_name='tutor_availabilities')
    op.drop_constraint(op.f('uq_tutor_availability_slot'), 'tutor_availabilities', type_='unique')
    op.create_index(op.f('ix_tutor_availabilities_id'), 'tutor_availabilities', ['id'], unique=False)
    op.drop_index(op.f('ix_tutor_certificates_tutor_profile_id'), table_name='tutor_certificates')
    op.create_index(op.f('ix_tutor_certificates_id'), 'tutor_certificates', ['id'], unique=False)
    op.drop_index(op.f('ix_tutor_educations_tutor_profile_id'), table_name='tutor_educations')
    op.create_index(op.f('ix_tutor_educations_id'), 'tutor_educations', ['id'], unique=False)
    op.drop_index(op.f('idx_tutor_profiles_price'), table_name='tutor_profiles')
    op.drop_index(op.f('idx_tutor_profiles_rating'), table_name='tutor_profiles')
    op.drop_index(op.f('idx_tutor_profiles_status'), table_name='tutor_profiles')
    op.drop_index(op.f('ix_tutor_profiles_location_id'), table_name='tutor_profiles')
    op.drop_index(op.f('ix_tutor_profiles_status'), table_name='tutor_profiles')
    op.drop_index(op.f('ix_tutor_profiles_user_id'), table_name='tutor_profiles')
    op.drop_index(op.f('ix_tutor_profiles_verified'), table_name='tutor_profiles')
    op.create_index(op.f('ix_tutor_profiles_id'), 'tutor_profiles', ['id'], unique=False)
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.drop_index(op.f('ix_tutor_profiles_id'), table_name='tutor_profiles')
    op.create_index(op.f('ix_tutor_profiles_verified'), 'tutor_profiles', ['verified'], unique=False)
    op.create_index(op.f('ix_tutor_profiles_user_id'), 'tutor_profiles', ['user_id'], unique=False)
    op.create_index(op.f('ix_tutor_profiles_status'), 'tutor_profiles', ['status'], unique=False)
    op.create_index(op.f('ix_tutor_profiles_location_id'), 'tutor_profiles', ['location_id'], unique=False)
    op.create_index(op.f('idx_tutor_profiles_status'), 'tutor_profiles', ['status'], unique=False)
    op.create_index(op.f('idx_tutor_profiles_rating'), 'tutor_profiles', [sa.literal_column('rating DESC')], unique=False)
    op.create_index(op.f('idx_tutor_profiles_price'), 'tutor_profiles', ['price_per_hour'], unique=False)
    op.drop_index(op.f('ix_tutor_educations_id'), table_name='tutor_educations')
    op.create_index(op.f('ix_tutor_educations_tutor_profile_id'), 'tutor_educations', ['tutor_profile_id'], unique=False)
    op.drop_index(op.f('ix_tutor_certificates_id'), table_name='tutor_certificates')
    op.create_index(op.f('ix_tutor_certificates_tutor_profile_id'), 'tutor_certificates', ['tutor_profile_id'], unique=False)
    op.drop_index(op.f('ix_tutor_availabilities_id'), table_name='tutor_availabilities')
    op.create_unique_constraint(op.f('uq_tutor_availability_slot'), 'tutor_availabilities', ['tutor_profile_id', 'day_of_week', 'start_time', 'end_time'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tutor_availabilities_tutor_profile_id'), 'tutor_availabilities', ['tutor_profile_id'], unique=False)
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_slug'), table_name='subjects')
    op.create_index(op.f('ix_subjects_slug'), 'subjects', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_subjects_slug'), 'subjects', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_reviews_id'), table_name='reviews')
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_tutor_profile_id'), 'reviews', ['tutor_profile_id'], unique=False)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=False)
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_index(op.f('ix_locations_slug'), table_name='locations')
    op.create_index(op.f('ix_locations_slug'), 'locations', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_locations_slug'), 'locations', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_levels_id'), table_name='levels')
    op.drop_index(op.f('ix_levels_slug'), table_name='levels')
    op.create_index(op.f('ix_levels_slug'), 'levels', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_levels_slug'), 'levels', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
