"""create_feedback_submissions_table

Revision ID: 5c6d071da512
Revises: 541daa51e051
Create Date: 2026-09-29 07:08:50.055590
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5c6d071da512'
down_revision: Union[str, None] = '541daa51e051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('found_information', sa.String(length=100), nullable=True),
    sa.Column('ease_of_use', sa.Integer(), nullable=True),
    sa.Column('tutor_priority', sa.String(length=100), nullable=True),
    sa.Column('price_range', sa.String(length=100), nullable=True),
    sa.Column('trust_level', sa.Integer(), nullable=True),
    sa.Column('usage_intention', sa.String(length=100), nullable=True),
    sa.Column('difficulty', sa.Text(), nullable=True),
    sa.Column('desired_features', sa.Text(), nullable=True),
    sa.Column('contact_requested', sa.Boolean(), nullable=False),
    sa.Column('contact_value', sa.String(length=255), nullable=True),
    sa.Column('answers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_submissions_id'), 'feedback_submissions', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_submissions_user_id'), 'feedback_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_submissions_user_id'), table_name='feedback_submissions')
    op.drop_index(op.f('ix_feedback_submissions_id'), table_name='feedback_submissions')
    op.drop_table('feedback_submissions')
    # ### end Alembic commands ###
